### ISSUE TITLE
Exception in ASGI Application When Running Sample from README

### ISSUE THREAD

**Issue by LucO77** [dudil/fastapi_msal#16]
**Describe the bug**
I'm get the following error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 77, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.9/site-packages/fastapi_msal/auth.py", line 83, in _post_token_route
    token: AuthToken = await self.handler.authorize_access_token(
  File "/usr/local/lib/python3.9/site-packages/fastapi_msal/security/msal_auth_code_handler.py", line 51, in authorize_access_token
    auth_token: AuthToken = await self.msal_app(cache=cache).finalize_auth_flow(
  File "/usr/local/lib/python3.9/site-packages/fastapi_msal/clients/async_conf_client.py", line 106, in finalize_auth_flow
    return AuthToken.parse_obj_debug(to_parse=auth_token)
  File "/usr/local/lib/python3.9/site-packages/fastapi_msal/models/base_auth_model.py", line 13, in parse_obj_debug
    debug_model: AuthModel = cls.parse_obj(obj=to_parse)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AuthToken
id_token
  field required (type=value_error.missing)
```

**To Reproduce**
1. Copied the code from the README
2. Changed the client_id, client_credential, tenant and secret_key 
3. Run the code
4. Goto http://localhost:5000/docs
5. Click the lock on the left of GET /users/me
6. In the popup, click Authorize
7. `auth errorError: Internal Server Error` is displayed in the popup and the above stack trace is in the console

**Expected behavior**
Would expect to get the confirmation popup as mentioned in the README on step 6.

**Environment Settings**
- OS: Ubuntu 20.04 (WSL2)
- Python Version: 3.9.5
- Packages Versions: [msal 1.17.0 / fastapi 0.73.0 / fastapi_msal 0.1.7]

**Additional context**
Tried changing my secret_key as mentioned in https://github.com/dudil/fastapi_msal/issues/1 but didn't change anything.

**Comment by SuperPommeDeTerre** [comment]
I'm currently facing the exact same problem on my project.
Any hint ?

**Comment by LucO77** [comment]
Sorry!  Never got around this error and never heard anything back...

**Comment by dudil** [comment]
Hi @LucO77 , @SuperPommeDeTerre - Sorry for the long delay, had been very much occupied lately.
had you also tried the template provided: https://github.com/dudil/ms-identity-python-webapp ?
I will look into the errors as described above but will take time as I'm involved in other projects.
Might be the readme is wrong and I'm better direct to the template instead

**Comment by csteele86** [comment]
I had this same issue and the answer provided by @Lewistrick did the trick! For me, it was the `client_credential`! Thank you!

**Comment by yuenherny** [comment]
I run into this issue when running on Kubernetes pod. Everything works on local and Docker container (local) but it seems to hit that error on Kubernetes. 

I double checked tenant ID, client ID and client credential. Its correct.

Any ideas? @dudil @Lewistrick

**Comment by dudil** [comment]
Hello @yuenherny - are you running multiple pods or only one?
If multiple, you will need to double check that the calling pod will get the response back as it holds the intermediate tokens of the handshake.
If single, it might be related to the reverse proxy settings.
Please let me know what exactly would be the case 👍

**Comment by yuenherny** [comment]
Hi @dudil , thanks for the prompt response. 

It is a single pod. I found out about the reverse proxy discussion as well in uvicorn [docs](https://www.uvicorn.org/deployment/#running-behind-nginx).

I am running uvicorn with `uvicorn.run("main:app", host="0.0.0.0", port=80, log_level="info", reload=True, forwarded_allow_ips="*")`

**Comment by dudil** [comment]
HI @yuenherny - I'm sorry as I don't have too much to check it out.
But might be this article helpful for your case?
https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

In a nutshell - MSAL is using OAuth to authenticate the users. Hence my guess you will need to follow up this part with the Kubernetes configuration.
I do hope this will be helpful direction for you 🙏

**Comment by yuenherny** [comment]
> > I had the same problem. For me it was a simple mistake of copying the values from the wrong place.
> > 
> > * `client_config.tenant` should be the tenant ID. In the Azure Portal, you can find this in the App Registration overview (the value of 'Directory (tenant) ID')
> > * `client_config.client_id` should be the application ID. This is also found in the App Registration overview (the value of 'Application (client) ID')
> > * `client_config.client_credential` is _not_ in the overview, but is found in the 'Certificates & secrets' (find it in the left menu under Manage), then go to the 'Client secrets' tab. You should copy the Value (the secret ID is not necessary). Note that you can only access this value once, after that it's hidden.
> > 
> > @LucO77 @SuperPommeDeTerre
> 
> Can you please assist by creating PR for the readme so it would be much more clear? That would be very much appreciated 🙏

On this, I would love to take this up if no one is on it yet 😄 @dudil

**Comment by dudil** [comment]
@yuenherny - would love that. Thank you!

**Comment by yuenherny** [comment]
Hi @dudil , I created this PR #22 as a response to your comment above. Please do have a look! Cheers.

**Comment by yuenherny** [comment]
Hi @dudil , I was meddling with the developer tools and I found this:
![image](https://github.com/dudil/fastapi_msal/assets/59016908/5b47babc-ce82-4391-96e2-67b7288b0a3c)

I am guessing this could be the cause of the error. Any ideas?
