### ISSUE TITLE
Question: How to access API outside of swagger page

### ISSUE THREAD

**Issue by jlerman44** [dudil/fastapi_msal#3]
Hello,

My exploration into this package is going well, but I have a few more questions as I try to get an optimal experience. Thanks for bearing with me :).

I would like to be able to call the API outside of the swagger page (e.g. from the command line with curl). 

I am getting:

2021-06-04T21:50:33.804149794Z [2021-06-04 21:50:33 +0000] [7] [ERROR] Exception in ASGI application
2021-06-04T21:50:33.804248696Z Traceback (most recent call last):
2021-06-04T21:50:33.804263696Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
2021-06-04T21:50:33.804271997Z     result = await app(self.scope, self.receive, self.send)
2021-06-04T21:50:33.804279297Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
2021-06-04T21:50:33.804286697Z     return await self.app(scope, receive, send)
2021-06-04T21:50:33.804293597Z   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
2021-06-04T21:50:33.804300897Z     await super().__call__(scope, receive, send)
2021-06-04T21:50:33.804321397Z   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
2021-06-04T21:50:33.804329098Z     await self.middleware_stack(scope, receive, send)
2021-06-04T21:50:33.804336098Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-06-04T21:50:33.804343398Z     raise exc from None
2021-06-04T21:50:33.804350098Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-06-04T21:50:33.804362998Z     await self.app(scope, receive, _send)
2021-06-04T21:50:33.804369798Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 75, in __call__
2021-06-04T21:50:33.804388099Z     await self.app(scope, receive, send_wrapper)
2021-06-04T21:50:33.804395799Z   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2021-06-04T21:50:33.804403099Z     raise exc from None
2021-06-04T21:50:33.804410099Z   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
2021-06-04T21:50:33.804514001Z     await self.app(scope, receive, sender)
2021-06-04T21:50:33.804522001Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
2021-06-04T21:50:33.804529501Z     await route.handle(scope, receive, send)
2021-06-04T21:50:33.804536701Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
2021-06-04T21:50:33.804544002Z     await self.app(scope, receive, send)
2021-06-04T21:50:33.804551002Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
2021-06-04T21:50:33.804558302Z     response = await func(request)
2021-06-04T21:50:33.804578902Z   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in app
2021-06-04T21:50:33.804587002Z     solved_result = await solve_dependencies(
2021-06-04T21:50:33.804594103Z   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 548, in solve_dependencies
2021-06-04T21:50:33.804603703Z     solved = await call(**sub_values)
2021-06-04T21:50:33.804610803Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/security/msal_scheme.py", line 47, in __call__
2021-06-04T21:50:33.804618203Z     token_claims: Optional[IDTokenClaims] = await self.handler.parse_id_token(
2021-06-04T21:50:33.804625203Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/security/msal_auth_code_handler.py", line 68, in parse_id_token
2021-06-04T21:50:33.804632603Z     auth_token: Optional[AuthToken] = await self.get_token_from_session(
2021-06-04T21:50:33.804639803Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/security/msal_auth_code_handler.py", line 89, in get_token_from_session
2021-06-04T21:50:33.804647304Z     return await AuthToken.load_from_session(
2021-06-04T21:50:33.804654304Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/models/base_auth_model.py", line 24, in load_from_session
2021-06-04T21:50:33.804661504Z     return session.load(model_cls=cls)
2021-06-04T21:50:33.804668404Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/core/session_manager.py", line 79, in load
2021-06-04T21:50:33.804675604Z     session: StrsDict = self._read_session()
2021-06-04T21:50:33.804682604Z   File "/usr/local/lib/python3.9/site-packages/fastapi_msal/core/session_manager.py", line 56, in _read_session
2021-06-04T21:50:33.804689804Z     raise IOError(
2021-06-04T21:50:33.804696504Z OSError: No session id, (Make sure you initialized the session by calling init_session)

My routes are protected with `Depends(msal_auth.scheme)`.

**Comment by jlerman44** [comment]
Do you suggest starting with 

```python
import requests
s = requests.Session()
s.get(base_url+"/_login_route")
```

and then get token using msal?

**Comment by jlerman44** [comment]
I got this to work. A session is required.  If you think a code sample would be helpful for the docs I can provide. It took some detailed configuring inside of Azure.  The session is a little awkward since you already have an access token, but I suppose it works.

**Comment by jlerman44** [comment]
@dudil - any idea how to get around the need for a session? Especially in cases where you already have a token you are ready to call the API with?  In these cases is a server side session necessary?

**Comment by dudil** [comment]
Hi @jlerman44 - for some reason I wasn't aware at all for this issue - sorry for the late reponse 😔
I will try to include a short example during the weekend, it will us to be more concrete as for what is working and what is not.

**Comment by jlerman44** [comment]
@dudil  thanks! that would be much appreciated. We are trying to connect to an API protected by fastapi_msal from a front end application (SPA).. We are struggling with how to establish the session with the backend. And of course the usual CORS issues.

**Comment by dudil** [comment]
@jlerman44 - I make a mess there with the session....
I will fix it + provide the example.

Highly appreciate your help here!

**Comment by dudil** [comment]
Hi @jlerman44 -
I've update the session code - please use version 0.1.6

As for code example I've taken the MASL code example for webapp and update it to use the fastapi_msal package.
Please review my fork https://github.com/dudil/ms-identity-python-webapp, make sure you are at the fastapi_msal branch.

( @rayluo - I hope you will like it, I originally thought to create a PR to your source code but after reviewing the differences I'm not sure that will work right. Anyway - thank you for the inspiration!)

This one is based on the server side session management and doesn't implement the CORS, yet.
CORS should be quite simple with fastapi middleware, I'll add it next.

I do hope you will find this useful!

**Comment by jlerman44** [comment]
@dudil  - this is a godsend. Thank you so much for it. We tested it, and it works. Now we will spread the word that this package is fully usable!

**Comment by jlerman44** [comment]
This issue can be closed.

**Comment by dudil** [comment]
> @dudil - this is a godsend. Thank you so much for it. We tested it, and it works. Now we will spread the word that this package is fully usable!

My pleasure @jlerman44. I hope you will find it useful and will do my best to assist if anything else arise.
